site_name: Dan's Cyber Stuff
nav:
  - Home: index.md
  - Bug Bounty Hunting:
    - OWASP Top 10 2025: owasp-top-10-2025.md
    - Reconnaissance: reconnaissance.md
    - Reporting & POC: reporting-and-poc.md
    - Tools: tools.md
    - Resources: resources.md
    - Web Application Testing:
      - Web Fundamentals: web-application-testing/web-fundamentals.md
      - Broken Access Control: web-application-testing/broken-access-control.md
      - SQL Injection: web-application-testing/sql-injection.md
      - Command Injection: web-application-testing/command-injection.md
      - NoSQL Injection: web-application-testing/nosql-injection.md
      - XSS: web-application-testing/xss.md
      - CSRF: web-application-testing/csrf.md
      - SSRF: web-application-testing/ssrf.md
      - XXE: web-application-testing/xxe.md
      - Security Misconfiguration: web-application-testing/security-misconfiguration.md
      - Authentication: web-application-testing/authentication.md
      - Business Logic Vulnerabilities: web-application-testing/business-logic-vulnerabilities.md
      - Insecure Deserialization: web-application-testing/insecure-deserialization.md
      - Path Traversal: web-application-testing/path-traversal.md
    - Android Application Testing:
      - Android Fundamentals: android-application-testing/android-fundamentals.md
      - Static Testing: android-application-testing/static-testing.md
      - Dynamic Testing: android-application-testing/dynamic-testing.md

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.code.copy

plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
